import { AppConfig } from '@/types/app-config';

export const DEFAULT_APP_CONFIG: AppConfig = {
  appName: 'My Web App',
  webUrl: 'https://example.com',
  packageName: 'com.mycompany.mywebapp',
  versionName: '1.0.0',
  versionCode: 1,
  minSdk: 21,
  targetSdk: 35,
  orientation: 'portrait',
  fullscreen: false,
  permissions: {
    camera: true,
    storageRead: true,
    storageWrite: true,
    locationFine: false,
    locationCoarse: false,
    recordAudio: false,
    notifications: true,
    vibrate: true,
    networkState: true,
    wakeLock: false,
    biometric: false,
    bluetooth: false,
  },
  branding: {
    iconType: 'preset',
    iconPresetId: 'globe',
    iconDataUrl: null,
    iconBgColor: '#4f46e5',
    iconShape: 'squircle',
    splashType: 'gradient',
    splashBgColor: '#0f172a',
    splashGradient: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
    splashDataUrl: null,
    splashDurationMs: 2000,
    splashAnimation: 'fade',
    splashShowTitle: true,
    splashTagline: 'Fast, secure mobile experience',
  },
  styling: {
    primaryColor: '#4f46e5',
    accentColor: '#818cf8',
    statusBarColor: '#ffffff',
    statusBarStyle: 'dark',
    navBarColor: '#ffffff',
    pullToRefresh: true,
    showProgressBar: true,
    progressBarColor: '#4f46e5',
    exitConfirmDialog: true,
  },
  webView: {
    javascriptEnabled: true,
    domStorageEnabled: true,
    databaseEnabled: true,
    cacheMode: 'default',
    userAgentType: 'mobile_chrome',
    customUserAgent: '',
    allowFileAccess: true,
    allowDownloads: true,
    hardwareAccelerated: true,
    clearCacheOnExit: false,
    openExternalLinksInBrowser: true,
    offlinePageEnabled: true,
    customOfflineMessage: 'You are currently offline. Please check your internet connection and try again.',
    enableZoomControls: false,
    allowMixedContent: false,
  },
};

export interface AppPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  config: Partial<AppConfig>;
  icon: string;
}

export const APP_PRESETS: AppPreset[] = [
  {
    id: 'ecommerce',
    name: 'E-Commerce Store',
    category: 'Retail & Shopping',
    description: 'Optimized for online shops, shopping carts, file uploads, and order notifications.',
    icon: 'ShoppingBag',
    config: {
      appName: 'ShopDirect',
      webUrl: 'https://demo.vercel.store',
      packageName: 'com.store.shopdirect',
      permissions: {
        camera: true,
        storageRead: true,
        storageWrite: true,
        locationFine: true,
        locationCoarse: true,
        recordAudio: false,
        notifications: true,
        vibrate: true,
        networkState: true,
        wakeLock: false,
        biometric: true,
        bluetooth: false,
      },
      branding: {
        iconType: 'preset',
        iconPresetId: 'shopping-bag',
        iconDataUrl: null,
        iconBgColor: '#059669',
        iconShape: 'squircle',
        splashType: 'gradient',
        splashBgColor: '#064e3b',
        splashGradient: 'linear-gradient(135deg, #065f46 0%, #022c22 100%)',
        splashDataUrl: null,
        splashDurationMs: 2200,
        splashAnimation: 'zoom',
        splashShowTitle: true,
        splashTagline: 'Discover trending deals & seamless checkout',
      },
      styling: {
        primaryColor: '#059669',
        accentColor: '#34d399',
        statusBarColor: '#ffffff',
        statusBarStyle: 'dark',
        navBarColor: '#ffffff',
        pullToRefresh: true,
        showProgressBar: true,
        progressBarColor: '#059669',
        exitConfirmDialog: true,
      },
    },
  },
  {
    id: 'saas_dashboard',
    name: 'SaaS Web App / Dashboard',
    category: 'Productivity & Tech',
    description: 'Hardware accelerated WebView with persistent auth, file attachments, and clean UI.',
    icon: 'LayoutDashboard',
    config: {
      appName: 'CloudDesk',
      webUrl: 'https://ui.shadcn.com',
      packageName: 'com.cloud.clouddesk',
      permissions: {
        camera: true,
        storageRead: true,
        storageWrite: true,
        locationFine: false,
        locationCoarse: false,
        recordAudio: true,
        notifications: true,
        vibrate: false,
        networkState: true,
        wakeLock: true,
        biometric: true,
        bluetooth: false,
      },
      branding: {
        iconType: 'preset',
        iconPresetId: 'layout-grid',
        iconDataUrl: null,
        iconBgColor: '#4f46e5',
        iconShape: 'rounded',
        splashType: 'gradient',
        splashBgColor: '#1e1b4b',
        splashGradient: 'linear-gradient(135deg, #312e81 0%, #0f172a 100%)',
        splashDataUrl: null,
        splashDurationMs: 1800,
        splashAnimation: 'fade',
        splashShowTitle: true,
        splashTagline: 'Your team workspace on mobile',
      },
      styling: {
        primaryColor: '#4f46e5',
        accentColor: '#818cf8',
        statusBarColor: '#0f172a',
        statusBarStyle: 'light',
        navBarColor: '#0f172a',
        pullToRefresh: false,
        showProgressBar: true,
        progressBarColor: '#6366f1',
        exitConfirmDialog: true,
      },
    },
  },
  {
    id: 'news_blog',
    name: 'News & Media Blog',
    category: 'Content & Publishing',
    description: 'Offline reading fallback, pull to refresh, dark mode status bar, and push alerts.',
    icon: 'Newspaper',
    config: {
      appName: 'DailyPulse',
      webUrl: 'https://news.ycombinator.com',
      packageName: 'com.media.dailypulse',
      permissions: {
        camera: false,
        storageRead: false,
        storageWrite: true,
        locationFine: false,
        locationCoarse: false,
        recordAudio: false,
        notifications: true,
        vibrate: true,
        networkState: true,
        wakeLock: false,
        biometric: false,
        bluetooth: false,
      },
      branding: {
        iconType: 'preset',
        iconPresetId: 'newspaper',
        iconDataUrl: null,
        iconBgColor: '#ea580c',
        iconShape: 'circle',
        splashType: 'solid',
        splashBgColor: '#c2410c',
        splashGradient: '',
        splashDataUrl: null,
        splashDurationMs: 1500,
        splashAnimation: 'slide_up',
        splashShowTitle: true,
        splashTagline: 'Breaking stories in real-time',
      },
      styling: {
        primaryColor: '#ea580c',
        accentColor: '#fb923c',
        statusBarColor: '#ffffff',
        statusBarStyle: 'dark',
        navBarColor: '#ffffff',
        pullToRefresh: true,
        showProgressBar: true,
        progressBarColor: '#ea580c',
        exitConfirmDialog: true,
      },
    },
  },
  {
    id: 'portfolio',
    name: 'Creative Portfolio',
    category: 'Showcase',
    description: 'Full-bleed immersive presentation, smooth gestures, and custom splash transition.',
    icon: 'Sparkles',
    config: {
      appName: 'StudioGallery',
      webUrl: 'https://dribbble.com',
      packageName: 'com.studio.gallery',
      fullscreen: false,
      permissions: {
        camera: false,
        storageRead: true,
        storageWrite: true,
        locationFine: false,
        locationCoarse: false,
        recordAudio: false,
        notifications: false,
        vibrate: true,
        networkState: true,
        wakeLock: true,
        biometric: false,
        bluetooth: false,
      },
      branding: {
        iconType: 'preset',
        iconPresetId: 'sparkles',
        iconDataUrl: null,
        iconBgColor: '#0f172a',
        iconShape: 'squircle',
        splashType: 'gradient',
        splashBgColor: '#09090b',
        splashGradient: 'linear-gradient(135deg, #18181b 0%, #09090b 100%)',
        splashDataUrl: null,
        splashDurationMs: 2500,
        splashAnimation: 'zoom',
        splashShowTitle: true,
        splashTagline: 'Design crafted for mobile excellence',
      },
      styling: {
        primaryColor: '#09090b',
        accentColor: '#a1a1aa',
        statusBarColor: '#09090b',
        statusBarStyle: 'light',
        navBarColor: '#09090b',
        pullToRefresh: true,
        showProgressBar: true,
        progressBarColor: '#f43f5e',
        exitConfirmDialog: false,
      },
    },
  },
];

export const PRESET_ICONS = [
  { id: 'globe', label: 'Web / Global', name: 'Globe' },
  { id: 'shopping-bag', label: 'E-Commerce', name: 'ShoppingBag' },
  { id: 'layout-grid', label: 'Dashboard', name: 'LayoutGrid' },
  { id: 'newspaper', label: 'News / Blog', name: 'Newspaper' },
  { id: 'sparkles', label: 'Creative / AI', name: 'Sparkles' },
  { id: 'rocket', label: 'Startup / Fast', name: 'Rocket' },
  { id: 'shield-check', label: 'Finance / Security', name: 'ShieldCheck' },
  { id: 'smartphone', label: 'App / Mobile', name: 'Smartphone' },
  { id: 'utensils', label: 'Food / Dining', name: 'Utensils' },
  { id: 'film', label: 'Media / Stream', name: 'Film' },
  { id: 'message-circle', label: 'Chat / Social', name: 'MessageCircle' },
  { id: 'heart-pulse', label: 'Health / Fitness', name: 'HeartPulse' },
];
